import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;

import org.xml.sax.SAXException;

import DOM.Finance;
import DOM.GetTime;
import DOM.XQJ4Search;
import Operate.newXML;
import Operate.saveData;

/*
 * Main.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class Main extends javax.swing.JFrame {

	/** Creates new form Main 
	 * @throws IOException 
	 * @throws SAXException 
	 * @throws TransformerException 
	 * @throws ParserConfigurationException */
	public Main(String id) throws ParserConfigurationException, TransformerException, SAXException, IOException {
		initComponents();
		
		File usr = new File("./"+id+".xml");
		if(!usr.exists())
		{
			newXML.creatNewXml(id);
		}
		initVar(id);
	}

	private void initVar(String id)
	{
		USRID = id;
		test = XQJ4Search.xqj4All(USRID);
		model = new DefaultTableModel(null, columns);
		jTable1.setModel(model);
		timeText.setText(GetTime.getTime());
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		timeText = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		showAllDataButton = new javax.swing.JButton();
		addDataButton = new javax.swing.JButton();
		deleteDataButton = new javax.swing.JButton();
		fixDataButton = new javax.swing.JButton();
		saveButton = new javax.swing.JButton();
		exitButton = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		keyWord = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jComboBox3 = new javax.swing.JComboBox();
		serchButton = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		extUsrButton = new javax.swing.JButton();
		extUsrDataButton = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel6 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		incomeText = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		outcomeText = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		lastMoney = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel1.setText("\u65f6\u95f4\uff1a");

		timeText.setText("2015\u5e744\u670829\u65e5 ");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGroup(
						jPanel1Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup()
												.addGap(77, 77, 77)
												.addComponent(jLabel1))
								.addGroup(
										jPanel1Layout.createSequentialGroup()
												.addGap(47, 47, 47)
												.addComponent(timeText)))
						.addContainerGap(89, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(timeText)
										.addContainerGap(53, Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		showAllDataButton.setText("\u663e\u793a\u5168\u90e8\u6570\u636e");
		showAllDataButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						showAllDataButtonActionPerformed(evt);
					}
				});

		addDataButton.setText("\u6dfb\u52a0");
		addDataButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addDataButtonActionPerformed(evt);
			}
		});

		deleteDataButton.setText("\u5220\u9664");
		deleteDataButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteDataButtonActionPerformed(evt);
			}
		});

		fixDataButton.setText("\u4fee\u6539\u6a21\u5f0f");
		fixDataButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fixDataButtonActionPerformed(evt);
			}
		});

		saveButton.setText("\u4fdd\u5b58");
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveButtonActionPerformed(evt);
			}
		});

		exitButton.setText("\u9000\u51fa\u7cfb\u7edf");
		exitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																showAllDataButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																182,
																Short.MAX_VALUE)
														.addComponent(
																addDataButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																182,
																Short.MAX_VALUE)
														.addComponent(
																deleteDataButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																182,
																Short.MAX_VALUE)
														.addComponent(
																fixDataButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																182,
																Short.MAX_VALUE)
														.addComponent(
																saveButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																182,
																Short.MAX_VALUE)
														.addComponent(
																exitButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																182,
																Short.MAX_VALUE))
										.addGap(21, 21, 21)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(37, 37, 37)
										.addComponent(showAllDataButton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												57, Short.MAX_VALUE)
										.addComponent(addDataButton).addGap(49,
												49, 49).addComponent(
												deleteDataButton).addGap(47,
												47, 47).addComponent(
												fixDataButton).addGap(48, 48,
												48).addComponent(saveButton)
										.addGap(45, 45, 45).addComponent(
												exitButton).addGap(66, 66, 66)));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel4.setText("\u5173\u952e\u5b57\uff1a");

		jLabel5.setText("\u6536\u652f\u7c7b\u578b\uff1a");

		jLabel6.setText("\u7c7b\u578b\uff1a");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"", "工资", "吃饭", "娱乐", "投资", "其他" }));

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"", "收入", "支出" }));

		serchButton.setText("\u641c\u7d22");
		serchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				serchButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel5)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																keyWord,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.Alignment.TRAILING,
																0, 316,
																Short.MAX_VALUE))
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				36,
																				36,
																				36)
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jComboBox3,
																				0,
																				200,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				serchButton)))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																jComboBox3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(21, 21, 21)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																keyWord,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																serchButton))
										.addGap(26, 26, 26)));

		jPanel4.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		extUsrButton.setText("\u5bfc\u51fa\u7528\u6237");

		extUsrDataButton.setText("\u5bfc\u51fa\u6570\u636e");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(extUsrButton).addContainerGap(
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel4Layout.createSequentialGroup().addContainerGap(12,
						Short.MAX_VALUE).addComponent(extUsrDataButton)
						.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(extUsrButton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												31, Short.MAX_VALUE)
										.addComponent(extUsrDataButton)
										.addContainerGap()));

		jPanel5.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setEnabled(false);
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444,
				Short.MAX_VALUE));

		jPanel6.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel7.setText("\u6536\u5165\uff1a");

		incomeText.setText("xxxxx");

		jLabel9.setText("\u652f\u51fa\uff1a");

		outcomeText.setText("xxxxxx");

		jLabel11.setText("\u5269\u4f59\u91d1\u989d\uff1a");

		lastMoney.setText("xxxxx");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(incomeText)
										.addGap(212, 212, 212)
										.addComponent(jLabel9)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(outcomeText)
										.addGap(174, 174, 174)
										.addComponent(jLabel11)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lastMoney)
										.addContainerGap(154, Short.MAX_VALUE)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																incomeText)
														.addComponent(jLabel9)
														.addComponent(
																outcomeText)
														.addComponent(jLabel11)
														.addComponent(lastMoney))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jPanel4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jPanel5,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel6,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGap(9, 9, 9)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel6,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void addDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		model.addRow(new String[7][]);
	}

	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		List<Finance> test = compare();
		saveData.insertData(test,USRID);
	}

	private void deleteDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int j = jTable1.getSelectedColumn()+1;
		int id= Integer.parseInt((String) jTable1.getValueAt(j, 0));
		for (int i = 0; i < test.size(); i++) {
			if (test.get(i).getId() == id) {
				test.remove(i);
			}
		}
		saveData.insertData(test,USRID);
		
		
		
		
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.removeRow(j);
	}

	private void fixDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		modifyMode = !modifyMode;
		jTable1.setEnabled(modifyMode);

	}

	//<<<<<<< HEAD
	//	private void serchButtonActionPerformed(java.awt.event.ActionEvent evt) {
	//		// TODO add your handling code here:
	//		System.out.println(jTable1.getValueAt(0, 0));
	//=======
	public String[][] getDataArray(List<Finance> finanlist, String[][] data) {
		for (int j = 0; j < finanlist.size(); j++) {
			int id = finanlist.get(j).getId();
			int num = finanlist.get(j).getNum();
			String financetype = finanlist.get(j).getFinancetype();
			String type = finanlist.get(j).getType();
			String spendingtime = finanlist.get(j).getSpendingtime();
			String remark = finanlist.get(j).getRemark();
			int userid = finanlist.get(j).getUserid();
			String finance[] = { String.valueOf(id), String.valueOf(num),
					financetype, type, spendingtime, remark,
					String.valueOf(userid) };
			data[j] = finance;
		}
		return data;
	}

	private void showAllDataButtonActionPerformed(java.awt.event.ActionEvent evt) {
		XQJ4Search xs = new XQJ4Search();
		//String usrid = "allen";//根据自己的需求填
		List<Finance> finanlist = new ArrayList<Finance>();
		finanlist = xs.xqj4All(USRID);
		String[][] data = new String[finanlist.size()][];
		model = new DefaultTableModel(getDataArray(finanlist, data), columns);
		jTable1.setModel(model);
		dataAll();
	}

	private void serchButtonActionPerformed(java.awt.event.ActionEvent evt) {
		String financetype = (String) jComboBox2.getSelectedItem();
		String type = (String) jComboBox3.getSelectedItem();
		String keyword = keyWord.getText();
		XQJ4Search xs = new XQJ4Search();
		//String userid = "allen";//根据需求自己填
		List<Finance> finanlist = new ArrayList<Finance>();
		finanlist = xs.xqj4Selected(USRID, financetype, type, keyword);
		String[][] data = new String[finanlist.size()][];
		model = new DefaultTableModel(getDataArray(finanlist, data), columns);
		jTable1.setModel(model);

		//>>>>>>> itas1994
	}

	/*
	 * 
	 * 以下为获取函数
	 */
	private List<Finance> getData() {
		List<Finance> out = new ArrayList<Finance>();
		int row = jTable1.getRowCount();
		int col = jTable1.getColumnCount();
		for (int i = 0; i < row; i++) {
			String r[] = new String[7];
			for (int j = 0; j < col; j++) {
				r[j] = (String) jTable1.getValueAt(i, j);
			}
			Finance finance = new Finance(Integer.parseInt(r[0]), Integer
					.parseInt(r[1]), r[2], r[3], r[4], r[5], Integer
					.parseInt(r[6]));
			out.add(finance);
		}
		return out;
	}

	private List<Finance> compare() {
		List<Finance> out = new ArrayList<Finance>();
		List<Finance> midData = new ArrayList<Finance>();
		out = test;
		midData = getData();
		for (Finance finance : midData) {
			int id = finance.getId();
			for (int i = 0; i < out.size(); i++) {
				if (out.get(i).getId() == id) {
					out.remove(i);
				}
			}
		}
		out.addAll(midData);
		System.out.println(22);
		return out;
	}

		private void dataAll()
		{
			int in = 0;
			int out = 0;
			for (int i = 0; i < jTable1.getRowCount(); i++) {
				if(((String)jTable1.getValueAt(i, 3)).equals("收入"))
				{
					in+=Integer.parseInt((String)jTable1.getValueAt(i, 1));
				}
				else{
					out+=Integer.parseInt((String)jTable1.getValueAt(i, 1));
				}
			}
			incomeText.setText(in+"");
			outcomeText.setText(out+"");
			lastMoney.setText((in-out)+"");
		}
	/**
	 * @param args the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new Main().setVisible(true);
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton addDataButton;
	private javax.swing.JButton deleteDataButton;
	private javax.swing.JButton exitButton;
	private javax.swing.JButton extUsrButton;
	private javax.swing.JButton extUsrDataButton;
	private javax.swing.JButton fixDataButton;
	private javax.swing.JLabel incomeText;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField keyWord;
	private javax.swing.JLabel lastMoney;
	private javax.swing.JLabel outcomeText;
	private javax.swing.JButton saveButton;
	private javax.swing.JButton serchButton;
	private javax.swing.JButton showAllDataButton;
	private javax.swing.JLabel timeText;
	// End of variables declaration//GEN-END:variables
	DefaultTableModel model = null;
	private static final String[] columns = { "编号", "数目", "账目类型", "类型", "时间",
			"备注", "用户编号" };
	private boolean modifyMode = false;
	private List<Finance> test;
	private String USRID;
	public String getUSRID() {
		return USRID;
	}

	public void setUSRID(String uSRID) {
		USRID = uSRID;
	}
}