import javax.swing.JOptionPane;

import DOM.DOM4User;
import DOM.GetTime;
import DOM.User;

/*
 * register.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class register extends javax.swing.JFrame {

	/** Creates new form register */
	public register() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		userName = new javax.swing.JLabel();
		password = new javax.swing.JLabel();
		repeatPwd = new javax.swing.JLabel();
		usrNameText = new javax.swing.JTextField();
		pwdText = new javax.swing.JPasswordField();
		repeatPwdText = new javax.swing.JPasswordField();
		yesButton = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		userName.setText("\u7528\u6237\u540d\uff1a");

		password.setText("\u5bc6\u7801\uff1a");

		repeatPwd.setText("\u91cd\u590d\u5bc6\u7801\uff1a");

		yesButton.setText("\u6ce8\u518c");
		yesButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				yesButtonActionPerformed(evt);
			}
		});

		resetButton.setText("\u91cd\u7f6e");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				yesButton)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				105,
																				Short.MAX_VALUE)
																		.addComponent(
																				resetButton))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								repeatPwd)
																						.addComponent(
																								userName)
																						.addComponent(
																								password))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addGap(
																												1,
																												1,
																												1)
																										.addComponent(
																												usrNameText,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												153,
																												Short.MAX_VALUE))
																						.addComponent(
																								pwdText,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								154,
																								Short.MAX_VALUE)
																						.addComponent(
																								repeatPwdText,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								154,
																								Short.MAX_VALUE))))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(38, 38, 38)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(userName)
														.addComponent(
																usrNameText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				33,
																				33,
																				33)
																		.addComponent(
																				password))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				39,
																				39,
																				39)
																		.addComponent(
																				pwdText,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(22, 22, 22)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(repeatPwd)
														.addComponent(
																repeatPwdText,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												52, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(yesButton)
														.addComponent(
																resetButton))
										.addGap(38, 38, 38)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		usrNameText.setText("");
		pwdText.setText("");
		repeatPwdText.setText("");
	}

	private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String name = usrNameText.getText();
		String pwd = pwdText.getText().hashCode() + "";
		String repwd = repeatPwdText.getText().hashCode() + "";
		if (pwd.equalsIgnoreCase(repwd)) {
			JOptionPane.showMessageDialog(null, "注册成功", "提示",
					JOptionPane.PLAIN_MESSAGE);
			User in = new User(name, pwd, GetTime.getTime());
			DOM4User.insertUser(in);
		} else {
			JOptionPane.showMessageDialog(null, "两次密码不一致，重输入", "提示",
					JOptionPane.PLAIN_MESSAGE);
		}
		this.setVisible(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new register().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel password;
	private javax.swing.JPasswordField pwdText;
	private javax.swing.JLabel repeatPwd;
	private javax.swing.JPasswordField repeatPwdText;
	private javax.swing.JButton resetButton;
	private javax.swing.JLabel userName;
	private javax.swing.JTextField usrNameText;
	private javax.swing.JButton yesButton;
	// End of variables declaration//GEN-END:variables

}